#!/usr/bin/env bash

export USER_ENV_HOME=~/Environment
. $USER_ENV_HOME/SetVariables.sh

current_branch=$(git rev-parse --abbrev-ref HEAD)
stash_message="git-switch away from $current_branch"

read -p "Branch name: " new_branch

git rev-parse --verify $new_branch

# $? == 0 means local branch with <branch-name> exists.

git stash save $stash_message
if [ $? = 0 ]
then
    git co $new_branch
else
    git co master
    git pull
    git co -b $new_branch
fi
